stages:
    - build
    - deploy
    - play
cache:
    key: ${CI_PROJECT_ID}
    paths:
        - .gradle/

push_github:
    stage: deploy
    only:
        - nightly
    script:
        - curl https://keystore.reallserver.cn/gitlab-sshkey/github-key.env -o /tmp/github-key.env -u gitlab:${key_store_passwd}
        - . /tmp/github-key.env
        - git push -f --set-upstream https://${GITHUB_ACCESS_KEY}@github.com/telegram-sms/telegram-sms.git HEAD:refs/heads/${CI_COMMIT_REF_NAME}

release_github:
    dependencies:
        - build
    only:
        - master
    stage: deploy
    script:
        - curl https://keystore.reallserver.cn/gitlab-sshkey/github-key.env -o /tmp/github-key.env -u gitlab:${key_store_passwd}
        - . /tmp/github—key.env
        - export TAG=${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}-$(date "+%Y%m%d%H%M")
        - git push --set-upstream https://${GITHUB_ACCESS_KEY}@github.com/telegram-sms/telegram-sms.git HEAD:refs/heads/${CI_COMMIT_REF_NAME}
        - /opt/github-release-upload.sh github_api_token=${GITHUB_ACCESS_KEY} owner=telegram-sms repo=telegram-sms tag=$TAG filename="./app/build/outputs/apk/release/app-release.apk" pre_release="false"
        - git clone https://github.com/telegram-sms/get-telegram-sms.reall.uk.git config
        - cd config
        - echo \{\"version\":${CI_PIPELINE_ID},\"name\":\"${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}\"\,\"download_link\":\"https://github.com/telegram-sms/telegram-sms/releases/download/${TAG}/app-release.apk\"} > version.json
        - git config --global user.email "reall_network@hotmail.com"
        - git config --global user.name ${CI_RUNNER_DESCRIPTION}
        - git add .
        - git commit -m ${TAG}
        - git push -f --set-upstream https://${GITHUB_ACCESS_KEY}@github.com/telegram-sms/get-telegram-sms.reall.uk.git HEAD:refs/heads/$CI_COMMIT_REF_NAME
        - cd ..
        - git clone https://git.reallserver.cn/qwe7002/telegram-sms.wiki.git wiki
        - cd wiki
        - git push -f --set-upstream https://${GITHUB_ACCESS_KEY}@github.com/telegram-sms/telegram-sms.wiki.git HEAD:refs/heads/$CI_COMMIT_REF_NAME
build:
    image: jangrewe/gitlab-ci-android:latest
    stage: build
    script:
        - export VERSION_CODE=${CI_PIPELINE_ID}
        - export VERSION_NAME=${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
        - curl https://keystore.reallserver.cn/android/telegram-sms/keys.jks -o app/keys.jks -u gitlab:${key_store_passwd}
        - curl https://keystore.reallserver.cn/android/telegram-sms/keystore.env -o /tmp/keystore.env -u gitlab:${key_store_passwd}
        - . /tmp/keystore.env
        - export GRADLE_USER_HOME=$(pwd)/.gradle
        - touch $(pwd)/.gradle/gradle.properties && echo "org.gradle.daemon=true" >> $(pwd)/.gradle/gradle.properties
        - echo -e "systemProp.http.nonProxyHosts=dl.google.com\n systemProp.http.proxyHost=192.168.3.8\n systemProp.http.proxyPort=1080\n systemProp.https.proxyHost=192.168.3.8\n systemProp.https.proxyPort=1080\n org.gradle.jvmargs=-Xmx1536m\n org.gradle.parallel=true\n android.enableJetifier=true\n android.useAndroidX=true" >> gradle.properties
        - chmod +x ./gradlew
        - ./gradlew assembleRelease
    artifacts:
        paths:
            - app/build/outputs/apk/release/app-release.apk
        expire_in: 1 week

