stages:
    - build
    - deploy
    - play
cache:
    key: ${CI_PROJECT_ID}
    paths:
        - .gradle/

push_github:
    stage: deploy
    only:
        - nightly
    script:
        - eval $(ssh-agent -s)
        - ssh-add - <<< $(curl https://keystore.reallserver.cn/gitlab-sshkey/id_ecdsa -u gitlab:${key_store_passwd})
        - git push -f --set-upstream git@github.com:telegram-sms/telegram-sms.git HEAD:refs/heads/${CI_COMMIT_REF_NAME}

release_github:
    dependencies:
        - build
    only:
        - master
    stage: deploy
    script:
        - curl https://keystore.reallserver.cn/gitlab-sshkey/id_ecdsa -o .reall_network/deploy.key -u gitlab:${key_store_passwd}
        - curl https://keystore.reallserver.cn/gitlab-sshkey/github-key.env -o .reall_network/github-key.env -u gitlab:${key_store_passwd}
        - . .reall_network/github-key.env
        - git config --global user.email "reall_network@hotmail.com"
        - git config --global user.name ${CI_RUNNER_DESCRIPTION}
        - eval $(ssh-agent -s)
        - chmod 0600 .reall_network/deploy.key
        - ssh-add .reall_network/deploy.key
        - git push --set-upstream git@github.com:telegram-sms/telegram-sms.git HEAD:refs/heads/${CI_COMMIT_REF_NAME}
        - export TAG=${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}-$(date "+%Y%m%d%H%M")
        - /opt/github-release-upload.sh github_api_token=${GITHUB_ACCESS_KEY} owner=telegram-sms repo=telegram-sms tag=$TAG filename="./app/build/outputs/apk/release/app-release.apk" pre_release="false"
        - git clone git@github.com:telegram-sms/get-telegram-sms.reall.uk.git config
        - cd config
        - export MD5=$(md5sum "./app/build/outputs/apk/release/app-release.apk" |cut -d ' ' -f1)
        - echo \{\"version\":${CI_PIPELINE_ID},\"name\":\"${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}\"\,\"download_link\":\"https://github.com/telegram-sms/telegram-sms/releases/download/${TAG}/app-release.apk\",\"check_sum\":\"${MD5}\"} > version.json
        - git add .
        - git commit -m ${TAG}
        - git push --set-upstream git@github.com:telegram-sms/get-telegram-sms.reall.uk.git -f HEAD:refs/heads/$CI_COMMIT_REF_NAME
        - cd ..
        - git clone https://git.reallserver.cn/qwe7002/telegram-sms.wiki.git wiki
        - cd wiki
        - git push -f --set-upstream git@github.com:telegram-sms/telegram-sms.wiki.git HEAD:refs/heads/$CI_COMMIT_REF_NAME
build:
    image: alvrme/alpine-android:android-29
    stage: build
    script:
        - export VERSION_CODE=${CI_PIPELINE_ID}
        - export VERSION_NAME=${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
        - curl https://keystore.reallserver.cn/android/telegram-sms/keys.jks -o app/keys.jks -u gitlab:${key_store_passwd}
        - curl https://keystore.reallserver.cn/android/telegram-sms/keystore.env -o .reall_network/keystore.env -u gitlab:${key_store_passwd}
        - . .reall_network/keystore.env
        - export GRADLE_USER_HOME=$(pwd)/.gradle
        - echo -e "org.gradle.jvmargs=-Xmx1536m -DsocksProxyHost=proxy.reallserver.cn -DsocksProxyPort=1086 -DsocksNonProxyHosts=dl.google.com\n org.gradle.parallel=true\n android.enableJetifier=true\n android.useAndroidX=true" >> gradle.properties
        - chmod +x ./gradlew
        - ./gradlew assembleRelease
    artifacts:
        paths:
            - app/build/outputs/apk/release/app-release.apk
        expire_in: 1 week

